# Generated by Django 4.2.11 on 2024-04-15 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0002_task_executors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(blank=True, null=True, related_name='executors', to=settings.AUTH_USER_MODEL),
        ),
    ]
