# Generated by Django 4.2.11 on 2024-04-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_discussion_task_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanban.discussion'),
        ),
    ]
